name: 'GAPSI Size Checker'
description: 'Check PR total lines changed'
inputs:
  max_lines_changed:
    description: 'Numero maximo de lineas permitidas'
    required: true
    default: '200'
  target_branch:
    description: La rama a la que se hace el PR
    required: true
    default: main
runs:
  using: "composite"
  steps:
    - id: get_total_lines_changed
      run: |
        size=$(git diff --stat origin/${{ inputs.target_branch }} \
        | grep -v .lock \
        | awk -F"|" '{ print $2 }' \
        | awk '{ print $1 }' \
        | sed '/^$/d' \
        | paste -sd+ - \
        | bc)
        echo "size=${size}" >> $GITHUB_ENV
        echo ""
        echo "Total de lineas modificadas: "
        echo $size
      shell: bash
    - run: |
        if [[ $size -gt ${{ inputs.max_lines_changed }} ]]
        then
          echo "Warning - total lines changed is greater than" ${{ inputs.max_lines_changed }}.
          echo "Please consider breaking this PR down."
          exit 1
        fi
      shell: bash
